
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class BooleanAnimationBase : AnimationTimeline
{
	protected BooleanAnimationBase () { }

	public override sealed Type TargetPropertyType { get { return typeof (bool); } }

	public new BooleanAnimationBase Clone ()
	{
		throw new NotImplementedException ();
	} 

	public override sealed object GetCurrentValue (object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
	{
		return GetCurrentValue ((bool)defaultOriginValue, (bool) defaultDestinationValue, animationClock);
	}

	protected abstract bool GetCurrentValueCore (bool defaultOriginValue, bool defaultDestinationValue, AnimationClock animationClock);


	public bool GetCurrentValue (bool defaultOriginValue, bool defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}


}


}
