
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class ByteKeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty; /* XXX initialize */
	public static readonly DependencyProperty ValueProperty; /* XXX initialize */

	protected ByteKeyFrame ()
	{
	}

	protected ByteKeyFrame (byte value)
	{
	}

	protected ByteKeyFrame (byte value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { return (KeyTime)GetValue (KeyTimeProperty); }
		set { SetValue (KeyTimeProperty, value); }
	}

	public byte Value {
		get { return (byte)GetValue (ValueProperty); }
		set { SetValue (ValueProperty, value); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (byte)value; }
	}

	public byte InterpolateValue (byte baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract byte InterpolateValueCore (byte baseValue, double keyFrameProgress);
}


}
