
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class CharAnimationBase : AnimationTimeline
{
	protected CharAnimationBase () { }

	public override sealed Type TargetPropertyType { get { return typeof (char); } }

	public new CharAnimationBase Clone ()
	{
		throw new NotImplementedException ();
	} 

	public override sealed object GetCurrentValue (object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
	{
		return GetCurrentValue ((char)defaultOriginValue, (char) defaultDestinationValue, animationClock);
	}

	protected abstract char GetCurrentValueCore (char defaultOriginValue, char defaultDestinationValue, AnimationClock animationClock);


	public char GetCurrentValue (char defaultOriginValue, char defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}


}


}
