
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class CharKeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty; /* XXX initialize */
	public static readonly DependencyProperty ValueProperty; /* XXX initialize */

	protected CharKeyFrame ()
	{
	}

	protected CharKeyFrame (char value)
	{
	}

	protected CharKeyFrame (char value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { return (KeyTime)GetValue (KeyTimeProperty); }
		set { SetValue (KeyTimeProperty, value); }
	}

	public char Value {
		get { return (char)GetValue (ValueProperty); }
		set { SetValue (ValueProperty, value); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (char)value; }
	}

	public char InterpolateValue (char baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract char InterpolateValueCore (char baseValue, double keyFrameProgress);
}


}
