
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Windows.Media.Animation;

namespace System.Windows.Media.Animation {


	public class ClockCollection : Animatable, ICollection<Clock>, IList<Clock>, ICollection, IList, IFormattable
	{
		List<Clock> list;

		public struct Enumerator : IEnumerator<Clock>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public Clock Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public ClockCollection ()
		{
			list = new List<Clock>();
		}

		public ClockCollection (IEnumerable<Clock> values)
		{
			list = new List<Clock> (values);
		}

		public ClockCollection (int length)
		{
			list = new List<Clock> (length);
		}

		public new ClockCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public new ClockCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		public bool Contains (Clock value)
		{
			return list.Contains (value);
		}

		public bool Remove (Clock value)
		{
			return list.Remove (value);
		}

		public int IndexOf (Clock value)
		{
			return list.IndexOf (value);
		}

		public void Add (Clock value)
		{
			list.Add (value);
		}

		public void Clear ()
		{
			list.Clear ();
		}

		public void CopyTo (Clock[] array, int arrayIndex)
		{
			list.CopyTo (array, arrayIndex);
		}

		public void Insert (int index, Clock value)
		{
			list.Insert (index, value);
		}

		public void RemoveAt (int index)
		{
			list.RemoveAt (index);
		}

		public int Count {
			get { return list.Count; }
		}

		public Clock this[int index] {
			get { return list[index]; }
			set { list[index] = value; }
		}

		public static ClockCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<Clock>.IsReadOnly {
			get { return false; }
		}

		public Enumerator GetEnumerator()
		{
			return new Enumerator();
		}

		IEnumerator<Clock> IEnumerable<Clock>.GetEnumerator()
		{
			return GetEnumerator ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			return GetEnumerator();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((Clock[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (Clock)value; }
		}

		int IList.Add (object value)
		{
			Add ((Clock)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((Clock)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((Clock)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (Clock)value);
		}

		void IList.Remove (object value)
		{
			Remove ((Clock)value);
		}

		public override string ToString ()
		{
			throw new NotImplementedException ();
		}

		public string ToString (IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}

		string IFormattable.ToString (string format, IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}


		protected override Freezable CreateInstanceCore ()
		{
			return new ClockCollection();
		}

		protected override void GetAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}
	}
}
