
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class DecimalAnimationBase : AnimationTimeline
{
	protected DecimalAnimationBase () { }

	public override sealed Type TargetPropertyType { get { return typeof (Decimal); } }

	public new DecimalAnimationBase Clone ()
	{
		throw new NotImplementedException ();
	} 

	public override sealed object GetCurrentValue (object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
	{
		return GetCurrentValue ((Decimal)defaultOriginValue, (Decimal) defaultDestinationValue, animationClock);
	}

	protected abstract Decimal GetCurrentValueCore (Decimal defaultOriginValue, Decimal defaultDestinationValue, AnimationClock animationClock);


	public Decimal GetCurrentValue (Decimal defaultOriginValue, Decimal defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}


}


}
