
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class DecimalKeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty
				= DependencyProperty.Register ("KeyTime", typeof (KeyTime), typeof (DecimalKeyFrame));

	public static readonly DependencyProperty ValueProperty
				= DependencyProperty.Register ("Value", typeof (Decimal), typeof (DecimalKeyFrame));

	protected DecimalKeyFrame ()
	{
	}

	protected DecimalKeyFrame (Decimal value)
	{
	}

	protected DecimalKeyFrame (Decimal value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { return (KeyTime)GetValue (KeyTimeProperty); }
		set { SetValue (KeyTimeProperty, value); }
	}

	public Decimal Value {
		get { return (Decimal)GetValue (ValueProperty); }
		set { SetValue (ValueProperty, value); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (Decimal)value; }
	}

	public Decimal InterpolateValue (Decimal baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract Decimal InterpolateValueCore (Decimal baseValue, double keyFrameProgress);
}


}
