
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscreteByteKeyFrame : ByteKeyFrame
{
	byte value;
	KeyTime keyTime;

	public DiscreteByteKeyFrame ()
	{
	}

	public DiscreteByteKeyFrame (byte value)
	{
		this.value = value;
		// XXX keytime?
	}

	public DiscreteByteKeyFrame (byte value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		return new DiscreteByteKeyFrame ();
	}

	protected override byte InterpolateValueCore (byte baseValue, double keyFrameProgress)
	{
		return keyFrameProgress == 1.0 ? value : baseValue;
	}
}


}
