
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscreteInt16KeyFrame : Int16KeyFrame
{

	public DiscreteInt16KeyFrame ()
	{
	}

	public DiscreteInt16KeyFrame (short value)
	{
	}

	public DiscreteInt16KeyFrame (short value, KeyTime keyTime)
	{
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override short InterpolateValueCore (short baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}
}


}
