
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscreteRectKeyFrame : RectKeyFrame
{

	public DiscreteRectKeyFrame ()
	{
	}

	public DiscreteRectKeyFrame (Rect value)
	{
	}

	public DiscreteRectKeyFrame (Rect value, KeyTime keyTime)
	{
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Rect InterpolateValueCore (Rect baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}
}


}
