
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscreteColorKeyFrame : ColorKeyFrame
{
	Color value;
	KeyTime keyTime;

	public DiscreteColorKeyFrame ()
	{
	}

	public DiscreteColorKeyFrame (Color value)
	{
		this.value = value;
		// XXX keytime?
	}

	public DiscreteColorKeyFrame (Color value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		return new DiscreteColorKeyFrame ();
	}

	protected override Color InterpolateValueCore (Color baseValue, double keyFrameProgress)
	{
		return keyFrameProgress == 1.0 ? value : baseValue;
	}
}


}
