
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscreteSizeKeyFrame : SizeKeyFrame
{

	public DiscreteSizeKeyFrame ()
	{
	}

	public DiscreteSizeKeyFrame (Size value)
	{
	}

	public DiscreteSizeKeyFrame (Size value, KeyTime keyTime)
	{
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Size InterpolateValueCore (Size baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}
}


}
