
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscreteMatrixKeyFrame : MatrixKeyFrame
{
	Matrix value;
	KeyTime keyTime;

	public DiscreteMatrixKeyFrame ()
	{
	}

	public DiscreteMatrixKeyFrame (Matrix value)
	{
		this.value = value;
		// XXX keytime?
	}

	public DiscreteMatrixKeyFrame (Matrix value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Matrix InterpolateValueCore (Matrix baseValue, double keyFrameProgress)
	{
		return keyFrameProgress == 1.0 ? value : baseValue;
	}
}


}
