
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscreteSizeKeyFrame : SizeKeyFrame
{
	Size value;
	KeyTime keyTime;

	public DiscreteSizeKeyFrame ()
	{
	}

	public DiscreteSizeKeyFrame (Size value)
	{
		this.value = value;
		// XXX keytime?
	}

	public DiscreteSizeKeyFrame (Size value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		return new DiscreteSizeKeyFrame ();
	}

	protected override Size InterpolateValueCore (Size baseValue, double keyFrameProgress)
	{
		return keyFrameProgress == 1.0 ? value : baseValue;
	}
}


}
