
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscreteStringKeyFrame : StringKeyFrame
{

	public DiscreteStringKeyFrame ()
	{
	}

	public DiscreteStringKeyFrame (String value)
	{
	}

	public DiscreteStringKeyFrame (String value, KeyTime keyTime)
	{
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override String InterpolateValueCore (String baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}
}


}
