
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscreteObjectKeyFrame : ObjectKeyFrame
{

	public DiscreteObjectKeyFrame ()
	{
	}

	public DiscreteObjectKeyFrame (object value)
	{
	}

	public DiscreteObjectKeyFrame (object value, KeyTime keyTime)
	{
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override object InterpolateValueCore (object baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}
}


}
