
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscreteSingleKeyFrame : SingleKeyFrame
{

	public DiscreteSingleKeyFrame ()
	{
	}

	public DiscreteSingleKeyFrame (float value)
	{
	}

	public DiscreteSingleKeyFrame (float value, KeyTime keyTime)
	{
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override float InterpolateValueCore (float baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}
}


}
