
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscreteByteKeyFrame : ByteKeyFrame
{

	public DiscreteByteKeyFrame ()
	{
	}

	public DiscreteByteKeyFrame (byte value)
	{
	}

	public DiscreteByteKeyFrame (byte value, KeyTime keyTime)
	{
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override byte InterpolateValueCore (byte baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}
}


}
