
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscretePointKeyFrame : PointKeyFrame
{
	Point value;
	KeyTime keyTime;

	public DiscretePointKeyFrame ()
	{
	}

	public DiscretePointKeyFrame (Point value)
	{
		this.value = value;
		// XXX keytime?
	}

	public DiscretePointKeyFrame (Point value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		return new DiscretePointKeyFrame ();
	}

	protected override Point InterpolateValueCore (Point baseValue, double keyFrameProgress)
	{
		return keyFrameProgress == 1.0 ? value : baseValue;
	}
}


}
