
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DiscreteVectorKeyFrame : VectorKeyFrame
{
	Vector value;
	KeyTime keyTime;

	public DiscreteVectorKeyFrame ()
	{
	}

	public DiscreteVectorKeyFrame (Vector value)
	{
		this.value = value;
		// XXX keytime?
	}

	public DiscreteVectorKeyFrame (Vector value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Vector InterpolateValueCore (Vector baseValue, double keyFrameProgress)
	{
		return keyFrameProgress == 1.0 ? value : baseValue;
	}
}


}
