
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class DoubleAnimationBase : AnimationTimeline
{
	protected DoubleAnimationBase () { }

	public override sealed Type TargetPropertyType { get { return typeof (double); } }

	public new DoubleAnimationBase Clone ()
	{
		throw new NotImplementedException ();
	} 

	public override sealed object GetCurrentValue (object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
	{
		return GetCurrentValue ((double)defaultOriginValue, (double) defaultDestinationValue, animationClock);
	}

	protected abstract double GetCurrentValueCore (double defaultOriginValue, double defaultDestinationValue, AnimationClock animationClock);


	public double GetCurrentValue (double defaultOriginValue, double defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}


}


}
