
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class DoubleAnimation : DoubleAnimationBase
{
	public static readonly DependencyProperty ByProperty
				= DependencyProperty.Register ("By", typeof (double?), typeof (DoubleAnimation));
	public static readonly DependencyProperty FromProperty
				= DependencyProperty.Register ("From", typeof (double?), typeof (DoubleAnimation));
	public static readonly DependencyProperty ToProperty
				= DependencyProperty.Register ("To", typeof (double?), typeof (DoubleAnimation));

	public DoubleAnimation ()
	{
	}

	public DoubleAnimation (double toValue, Duration duration)
	{
	}

	public DoubleAnimation (double toValue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public DoubleAnimation (double fromValue, double toValue, Duration duration)
	{
	}

	public DoubleAnimation (double fromValue, double tovalue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public double? By {
		get { return (double?) GetValue (ByProperty); }
		set { SetValue (ByProperty, value); }
	}

	public double? From {
		get { return (double?) GetValue (FromProperty); }
		set { SetValue (FromProperty, value); }
	}

	public double? To {
		get { return (double?) GetValue (ToProperty); }
		set { SetValue (ToProperty, value); }
	}

	public bool IsAdditive {
		get { return (bool) GetValue (AnimationTimeline.IsAdditiveProperty); }
		set { SetValue (AnimationTimeline.IsAdditiveProperty, value); }
	}

	public bool IsCumulative {
		get { return (bool) GetValue (AnimationTimeline.IsCumulativeProperty); }
		set { SetValue (AnimationTimeline.IsCumulativeProperty, value); }
	}

	public new DoubleAnimation Clone ()
	{
		throw new NotImplementedException ();
	}

	protected override Freezable CreateInstanceCore ()
	{
		return new DoubleAnimation ();
	}

	protected override double GetCurrentValueCore (double defaultOriginValue, double defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}
}


}
