
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class Int16Animation : Int16AnimationBase
{
	public static readonly DependencyProperty ByProperty; /* XXX initialize */
	public static readonly DependencyProperty FromProperty; /* XXX initialize */
	public static readonly DependencyProperty ToProperty; /* XXX initialize */

	public Int16Animation ()
	{
	}

	public Int16Animation (short toValue, Duration duration)
	{
	}

	public Int16Animation (short toValue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public Int16Animation (short fromValue, short toValue, Duration duration)
	{
	}

	public Int16Animation (short fromValue, short tovalue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public short? By {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public short? From {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public short? To {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public bool IsAdditive {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public bool IsCumulative {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public new Int16Animation Clone ()
	{
		throw new NotImplementedException ();
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override short GetCurrentValueCore (short defaultOriginValue, short defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}
}


}
