
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class Int16KeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty
				= DependencyProperty.Register ("KeyTime", typeof (KeyTime), typeof (Int16KeyFrame));

	public static readonly DependencyProperty ValueProperty
				= DependencyProperty.Register ("Value", typeof (short), typeof (Int16KeyFrame));

	protected Int16KeyFrame ()
	{
	}

	protected Int16KeyFrame (short value)
	{
	}

	protected Int16KeyFrame (short value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { return (KeyTime)GetValue (KeyTimeProperty); }
		set { SetValue (KeyTimeProperty, value); }
	}

	public short Value {
		get { return (short)GetValue (ValueProperty); }
		set { SetValue (ValueProperty, value); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (short)value; }
	}

	public short InterpolateValue (short baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract short InterpolateValueCore (short baseValue, double keyFrameProgress);
}


}
