
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class Int16AnimationBase : AnimationTimeline
{
	protected Int16AnimationBase () { }

	public override sealed Type TargetPropertyType { get { return typeof (short); } }

	public new Int16AnimationBase Clone ()
	{
		throw new NotImplementedException ();
	} 

	public override sealed object GetCurrentValue (object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
	{
		return GetCurrentValue ((short)defaultOriginValue, (short) defaultDestinationValue, animationClock);
	}

	protected abstract short GetCurrentValueCore (short defaultOriginValue, short defaultDestinationValue, AnimationClock animationClock);


	public short GetCurrentValue (short defaultOriginValue, short defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}


}


}
