
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class Int16KeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty; /* XXX initialize */
	public static readonly DependencyProperty ValueProperty; /* XXX initialize */

	protected Int16KeyFrame ()
	{
	}

	protected Int16KeyFrame (short value)
	{
	}

	protected Int16KeyFrame (short value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public short Value {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (short)value; }
	}

	public short InterpolateValue (short baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract short InterpolateValueCore (short baseValue, double keyFrameProgress);
}


}
