
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class Int32Animation : Int32AnimationBase
{
	public static readonly DependencyProperty ByProperty; /* XXX initialize */
	public static readonly DependencyProperty FromProperty; /* XXX initialize */
	public static readonly DependencyProperty ToProperty; /* XXX initialize */

	public Int32Animation ()
	{
	}

	public Int32Animation (int toValue, Duration duration)
	{
	}

	public Int32Animation (int toValue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public Int32Animation (int fromValue, int toValue, Duration duration)
	{
	}

	public Int32Animation (int fromValue, int tovalue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public int? By {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public int? From {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public int? To {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public bool IsAdditive {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public bool IsCumulative {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public new Int32Animation Clone ()
	{
		throw new NotImplementedException ();
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override int GetCurrentValueCore (int defaultOriginValue, int defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}
}


}
