
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class Int32KeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty; /* XXX initialize */
	public static readonly DependencyProperty ValueProperty; /* XXX initialize */

	protected Int32KeyFrame ()
	{
	}

	protected Int32KeyFrame (int value)
	{
	}

	protected Int32KeyFrame (int value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public int Value {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (int)value; }
	}

	public int InterpolateValue (int baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract int InterpolateValueCore (int baseValue, double keyFrameProgress);
}


}
