
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class Int32AnimationBase : AnimationTimeline
{
	protected Int32AnimationBase () { }

	public override sealed Type TargetPropertyType { get { return typeof (int); } }

	public new Int32AnimationBase Clone ()
	{
		throw new NotImplementedException ();
	} 

	public override sealed object GetCurrentValue (object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
	{
		return GetCurrentValue ((int)defaultOriginValue, (int) defaultDestinationValue, animationClock);
	}

	protected abstract int GetCurrentValueCore (int defaultOriginValue, int defaultDestinationValue, AnimationClock animationClock);


	public int GetCurrentValue (int defaultOriginValue, int defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}


}


}
