
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class Int64Animation : Int64AnimationBase
{
	public static readonly DependencyProperty ByProperty; /* XXX initialize */
	public static readonly DependencyProperty FromProperty; /* XXX initialize */
	public static readonly DependencyProperty ToProperty; /* XXX initialize */

	public Int64Animation ()
	{
	}

	public Int64Animation (long toValue, Duration duration)
	{
	}

	public Int64Animation (long toValue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public Int64Animation (long fromValue, long toValue, Duration duration)
	{
	}

	public Int64Animation (long fromValue, long tovalue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public long? By {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public long? From {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public long? To {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public bool IsAdditive {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public bool IsCumulative {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public new Int64Animation Clone ()
	{
		throw new NotImplementedException ();
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override long GetCurrentValueCore (long defaultOriginValue, long defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}
}


}
