
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class Int64KeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty
				= DependencyProperty.Register ("KeyTime", typeof (KeyTime), typeof (Int64KeyFrame));

	public static readonly DependencyProperty ValueProperty
				= DependencyProperty.Register ("Value", typeof (long), typeof (Int64KeyFrame));

	protected Int64KeyFrame ()
	{
	}

	protected Int64KeyFrame (long value)
	{
	}

	protected Int64KeyFrame (long value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { return (KeyTime)GetValue (KeyTimeProperty); }
		set { SetValue (KeyTimeProperty, value); }
	}

	public long Value {
		get { return (long)GetValue (ValueProperty); }
		set { SetValue (ValueProperty, value); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (long)value; }
	}

	public long InterpolateValue (long baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract long InterpolateValueCore (long baseValue, double keyFrameProgress);
}


}
