
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class Int64AnimationBase : AnimationTimeline
{
	protected Int64AnimationBase () { }

	public override sealed Type TargetPropertyType { get { return typeof (long); } }

	public new Int64AnimationBase Clone ()
	{
		throw new NotImplementedException ();
	} 

	public override sealed object GetCurrentValue (object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
	{
		return GetCurrentValue ((long)defaultOriginValue, (long) defaultDestinationValue, animationClock);
	}

	protected abstract long GetCurrentValueCore (long defaultOriginValue, long defaultDestinationValue, AnimationClock animationClock);


	public long GetCurrentValue (long defaultOriginValue, long defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}


}


}
