
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class Int64KeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty; /* XXX initialize */
	public static readonly DependencyProperty ValueProperty; /* XXX initialize */

	protected Int64KeyFrame ()
	{
	}

	protected Int64KeyFrame (long value)
	{
	}

	protected Int64KeyFrame (long value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public long Value {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (long)value; }
	}

	public long InterpolateValue (long baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract long InterpolateValueCore (long baseValue, double keyFrameProgress);
}


}
