
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class LinearInt32KeyFrame : Int32KeyFrame
{

	public LinearInt32KeyFrame ()
	{
	}

	public LinearInt32KeyFrame (int value)
	{
	}

	public LinearInt32KeyFrame (int value, KeyTime keyTime)
	{
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override int InterpolateValueCore (int baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}
}


}
