
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class LinearInt64KeyFrame : Int64KeyFrame
{

	public LinearInt64KeyFrame ()
	{
	}

	public LinearInt64KeyFrame (long value)
	{
	}

	public LinearInt64KeyFrame (long value, KeyTime keyTime)
	{
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override long InterpolateValueCore (long baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}
}


}
