
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class LinearPointKeyFrame : PointKeyFrame
{

	public LinearPointKeyFrame ()
	{
	}

	public LinearPointKeyFrame (Point value)
	{
	}

	public LinearPointKeyFrame (Point value, KeyTime keyTime)
	{
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Point InterpolateValueCore (Point baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}
}


}
