
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class LinearByteKeyFrame : ByteKeyFrame
{
	byte value;
	KeyTime keyTime;

	public LinearByteKeyFrame ()
	{
	}

	public LinearByteKeyFrame (byte value)
	{
		this.value = value;
		// XXX keytime?
	}

	public LinearByteKeyFrame (byte value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		return new LinearByteKeyFrame ();
	}

	protected override byte InterpolateValueCore (byte baseValue, double keyFrameProgress)
	{
		// standard linear interpolation
		return (byte)(baseValue + (value - baseValue) * keyFrameProgress);
	}
}


}
