
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class LinearInt64KeyFrame : Int64KeyFrame
{
	long value;
	KeyTime keyTime;

	public LinearInt64KeyFrame ()
	{
	}

	public LinearInt64KeyFrame (long value)
	{
		this.value = value;
		// XXX keytime?
	}

	public LinearInt64KeyFrame (long value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override long InterpolateValueCore (long baseValue, double keyFrameProgress)
	{
		// standard linear interpolation
		return (long)(baseValue + (value - baseValue) * keyFrameProgress);
	}
}


}
