
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class LinearRectKeyFrame : RectKeyFrame
{
	Rect value;
	KeyTime keyTime;

	public LinearRectKeyFrame ()
	{
	}

	public LinearRectKeyFrame (Rect value)
	{
		this.value = value;
		// XXX keytime?
	}

	public LinearRectKeyFrame (Rect value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Rect InterpolateValueCore (Rect baseValue, double keyFrameProgress)
	{
		// standard linear interpolation
		return new Rect (baseValue.X + (value.X - baseValue.X) * keyFrameProgress, baseValue.Y + (value.Y - baseValue.Y) * keyFrameProgress, baseValue.Width + (value.Width - baseValue.Width) * keyFrameProgress, baseValue.Height + (value.Height - baseValue.Height) * keyFrameProgress);
	}
}


}
