
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class LinearDoubleKeyFrame : DoubleKeyFrame
{
	double value;
	KeyTime keyTime;

	public LinearDoubleKeyFrame ()
	{
	}

	public LinearDoubleKeyFrame (double value)
	{
		this.value = value;
		// XXX keytime?
	}

	public LinearDoubleKeyFrame (double value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override double InterpolateValueCore (double baseValue, double keyFrameProgress)
	{
		// standard linear interpolation
		return (double)(baseValue + (value - baseValue) * keyFrameProgress);
	}
}


}
