
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class LinearPointKeyFrame : PointKeyFrame
{
	Point value;
	KeyTime keyTime;

	public LinearPointKeyFrame ()
	{
	}

	public LinearPointKeyFrame (Point value)
	{
		this.value = value;
		// XXX keytime?
	}

	public LinearPointKeyFrame (Point value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Point InterpolateValueCore (Point baseValue, double keyFrameProgress)
	{
		// standard linear interpolation
		return new Point (baseValue.X + (value.X - baseValue.X) * keyFrameProgress, baseValue.Y + (value.Y - baseValue.Y) * keyFrameProgress);;
	}
}


}
