
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class LinearInt32KeyFrame : Int32KeyFrame
{
	int value;
	KeyTime keyTime;

	public LinearInt32KeyFrame ()
	{
	}

	public LinearInt32KeyFrame (int value)
	{
		this.value = value;
		// XXX keytime?
	}

	public LinearInt32KeyFrame (int value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		return new LinearInt32KeyFrame ();
	}

	protected override int InterpolateValueCore (int baseValue, double keyFrameProgress)
	{
		// standard linear interpolation
		return (int)(baseValue + (value - baseValue) * keyFrameProgress);
	}
}


}
