
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class LinearVectorKeyFrame : VectorKeyFrame
{
	Vector value;
	KeyTime keyTime;

	public LinearVectorKeyFrame ()
	{
	}

	public LinearVectorKeyFrame (Vector value)
	{
		this.value = value;
		// XXX keytime?
	}

	public LinearVectorKeyFrame (Vector value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Vector InterpolateValueCore (Vector baseValue, double keyFrameProgress)
	{
		// standard linear interpolation
		return new Vector (baseValue.X + (value.X - baseValue.X) * keyFrameProgress, baseValue.Y + (value.Y - baseValue.Y) * keyFrameProgress);;
	}
}


}
