
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class LinearSingleKeyFrame : SingleKeyFrame
{
	float value;
	KeyTime keyTime;

	public LinearSingleKeyFrame ()
	{
	}

	public LinearSingleKeyFrame (float value)
	{
		this.value = value;
		// XXX keytime?
	}

	public LinearSingleKeyFrame (float value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		return new LinearSingleKeyFrame ();
	}

	protected override float InterpolateValueCore (float baseValue, double keyFrameProgress)
	{
		// standard linear interpolation
		return (float)(baseValue + (value - baseValue) * keyFrameProgress);
	}
}


}
