
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class LinearDecimalKeyFrame : DecimalKeyFrame
{
	Decimal value;
	KeyTime keyTime;

	public LinearDecimalKeyFrame ()
	{
	}

	public LinearDecimalKeyFrame (Decimal value)
	{
		this.value = value;
		// XXX keytime?
	}

	public LinearDecimalKeyFrame (Decimal value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Decimal InterpolateValueCore (Decimal baseValue, double keyFrameProgress)
	{
		// standard linear interpolation
		return (Decimal)((double)baseValue + ((double)value - (double)baseValue) * keyFrameProgress);
	}
}


}
