
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class MatrixAnimationBase : AnimationTimeline
{
	protected MatrixAnimationBase () { }

	public override sealed Type TargetPropertyType { get { return typeof (Matrix); } }

	public new MatrixAnimationBase Clone ()
	{
		throw new NotImplementedException ();
	} 

	public override sealed object GetCurrentValue (object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
	{
		return GetCurrentValue ((Matrix)defaultOriginValue, (Matrix) defaultDestinationValue, animationClock);
	}

	protected abstract Matrix GetCurrentValueCore (Matrix defaultOriginValue, Matrix defaultDestinationValue, AnimationClock animationClock);


	public Matrix GetCurrentValue (Matrix defaultOriginValue, Matrix defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}


}


}
