
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class MatrixKeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty
				= DependencyProperty.Register ("KeyTime", typeof (KeyTime), typeof (MatrixKeyFrame));

	public static readonly DependencyProperty ValueProperty
				= DependencyProperty.Register ("Value", typeof (Matrix), typeof (MatrixKeyFrame));

	protected MatrixKeyFrame ()
	{
	}

	protected MatrixKeyFrame (Matrix value)
	{
	}

	protected MatrixKeyFrame (Matrix value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { return (KeyTime)GetValue (KeyTimeProperty); }
		set { SetValue (KeyTimeProperty, value); }
	}

	public Matrix Value {
		get { return (Matrix)GetValue (ValueProperty); }
		set { SetValue (ValueProperty, value); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (Matrix)value; }
	}

	public Matrix InterpolateValue (Matrix baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract Matrix InterpolateValueCore (Matrix baseValue, double keyFrameProgress);
}


}
