
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class PointKeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty; /* XXX initialize */
	public static readonly DependencyProperty ValueProperty; /* XXX initialize */

	protected PointKeyFrame ()
	{
	}

	protected PointKeyFrame (Point value)
	{
	}

	protected PointKeyFrame (Point value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public Point Value {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (Point)value; }
	}

	public Point InterpolateValue (Point baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract Point InterpolateValueCore (Point baseValue, double keyFrameProgress);
}


}
