
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class RectKeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty; /* XXX initialize */
	public static readonly DependencyProperty ValueProperty; /* XXX initialize */

	protected RectKeyFrame ()
	{
	}

	protected RectKeyFrame (Rect value)
	{
	}

	protected RectKeyFrame (Rect value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public Rect Value {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (Rect)value; }
	}

	public Rect InterpolateValue (Rect baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract Rect InterpolateValueCore (Rect baseValue, double keyFrameProgress);
}


}
