
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class RectKeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty
				= DependencyProperty.Register ("KeyTime", typeof (KeyTime), typeof (RectKeyFrame));

	public static readonly DependencyProperty ValueProperty
				= DependencyProperty.Register ("Value", typeof (Rect), typeof (RectKeyFrame));

	protected RectKeyFrame ()
	{
	}

	protected RectKeyFrame (Rect value)
	{
	}

	protected RectKeyFrame (Rect value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { return (KeyTime)GetValue (KeyTimeProperty); }
		set { SetValue (KeyTimeProperty, value); }
	}

	public Rect Value {
		get { return (Rect)GetValue (ValueProperty); }
		set { SetValue (ValueProperty, value); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (Rect)value; }
	}

	public Rect InterpolateValue (Rect baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract Rect InterpolateValueCore (Rect baseValue, double keyFrameProgress);
}


}
