
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class RectAnimation : RectAnimationBase
{
	public static readonly DependencyProperty ByProperty; /* XXX initialize */
	public static readonly DependencyProperty FromProperty; /* XXX initialize */
	public static readonly DependencyProperty ToProperty; /* XXX initialize */

	public RectAnimation ()
	{
	}

	public RectAnimation (Rect toValue, Duration duration)
	{
	}

	public RectAnimation (Rect toValue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public RectAnimation (Rect fromValue, Rect toValue, Duration duration)
	{
	}

	public RectAnimation (Rect fromValue, Rect tovalue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public Rect? By {
		get { return (Rect?) GetValue (ByProperty); }
		set { SetValue (ByProperty, value); }
	}

	public Rect? From {
		get { return (Rect?) GetValue (FromProperty); }
		set { SetValue (FromProperty, value); }
	}

	public Rect? To {
		get { return (Rect?) GetValue (ToProperty); }
		set { SetValue (ToProperty, value); }
	}

	public bool IsAdditive {
		get { return (bool) GetValue (AnimationTimeline.IsAdditiveProperty); }
		set { SetValue (AnimationTimeline.IsAdditiveProperty, value); }
	}

	public bool IsCumulative {
		get { return (bool) GetValue (AnimationTimeline.IsCumulativeProperty); }
		set { SetValue (AnimationTimeline.IsCumulativeProperty, value); }
	}

	public new RectAnimation Clone ()
	{
		throw new NotImplementedException ();
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Rect GetCurrentValueCore (Rect defaultOriginValue, Rect defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}
}


}
