
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class RectAnimationBase : AnimationTimeline
{
	protected RectAnimationBase () { }

	public override sealed Type TargetPropertyType { get { return typeof (Rect); } }

	public new RectAnimationBase Clone ()
	{
		throw new NotImplementedException ();
	} 

	public override sealed object GetCurrentValue (object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
	{
		return GetCurrentValue ((Rect)defaultOriginValue, (Rect) defaultDestinationValue, animationClock);
	}

	protected abstract Rect GetCurrentValueCore (Rect defaultOriginValue, Rect defaultDestinationValue, AnimationClock animationClock);


	public Rect GetCurrentValue (Rect defaultOriginValue, Rect defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}


}


}
