
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class SingleAnimationBase : AnimationTimeline
{
	protected SingleAnimationBase () { }

	public override sealed Type TargetPropertyType { get { return typeof (float); } }

	public new SingleAnimationBase Clone ()
	{
		throw new NotImplementedException ();
	} 

	public override sealed object GetCurrentValue (object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
	{
		return GetCurrentValue ((float)defaultOriginValue, (float) defaultDestinationValue, animationClock);
	}

	protected abstract float GetCurrentValueCore (float defaultOriginValue, float defaultDestinationValue, AnimationClock animationClock);


	public float GetCurrentValue (float defaultOriginValue, float defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}


}


}
