
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class SingleKeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty
				= DependencyProperty.Register ("KeyTime", typeof (KeyTime), typeof (SingleKeyFrame));

	public static readonly DependencyProperty ValueProperty
				= DependencyProperty.Register ("Value", typeof (float), typeof (SingleKeyFrame));

	protected SingleKeyFrame ()
	{
	}

	protected SingleKeyFrame (float value)
	{
	}

	protected SingleKeyFrame (float value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { return (KeyTime)GetValue (KeyTimeProperty); }
		set { SetValue (KeyTimeProperty, value); }
	}

	public float Value {
		get { return (float)GetValue (ValueProperty); }
		set { SetValue (ValueProperty, value); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (float)value; }
	}

	public float InterpolateValue (float baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract float InterpolateValueCore (float baseValue, double keyFrameProgress);
}


}
