
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class SingleAnimation : SingleAnimationBase
{
	public static readonly DependencyProperty ByProperty
				= DependencyProperty.Register ("By", typeof (float?), typeof (SingleAnimation));
	public static readonly DependencyProperty FromProperty
				= DependencyProperty.Register ("From", typeof (float?), typeof (SingleAnimation));
	public static readonly DependencyProperty ToProperty
				= DependencyProperty.Register ("To", typeof (float?), typeof (SingleAnimation));

	public SingleAnimation ()
	{
	}

	public SingleAnimation (float toValue, Duration duration)
	{
	}

	public SingleAnimation (float toValue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public SingleAnimation (float fromValue, float toValue, Duration duration)
	{
	}

	public SingleAnimation (float fromValue, float tovalue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public float? By {
		get { return (float?) GetValue (ByProperty); }
		set { SetValue (ByProperty, value); }
	}

	public float? From {
		get { return (float?) GetValue (FromProperty); }
		set { SetValue (FromProperty, value); }
	}

	public float? To {
		get { return (float?) GetValue (ToProperty); }
		set { SetValue (ToProperty, value); }
	}

	public bool IsAdditive {
		get { return (bool) GetValue (AnimationTimeline.IsAdditiveProperty); }
		set { SetValue (AnimationTimeline.IsAdditiveProperty, value); }
	}

	public bool IsCumulative {
		get { return (bool) GetValue (AnimationTimeline.IsCumulativeProperty); }
		set { SetValue (AnimationTimeline.IsCumulativeProperty, value); }
	}

	public new SingleAnimation Clone ()
	{
		throw new NotImplementedException ();
	}

	protected override Freezable CreateInstanceCore ()
	{
		return new SingleAnimation ();
	}

	protected override float GetCurrentValueCore (float defaultOriginValue, float defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}
}


}
