
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class SingleAnimation : SingleAnimationBase
{
	public static readonly DependencyProperty ByProperty; /* XXX initialize */
	public static readonly DependencyProperty FromProperty; /* XXX initialize */
	public static readonly DependencyProperty ToProperty; /* XXX initialize */

	public SingleAnimation ()
	{
	}

	public SingleAnimation (float toValue, Duration duration)
	{
	}

	public SingleAnimation (float toValue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public SingleAnimation (float fromValue, float toValue, Duration duration)
	{
	}

	public SingleAnimation (float fromValue, float tovalue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public float? By {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public float? From {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public float? To {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public bool IsAdditive {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public bool IsCumulative {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public new SingleAnimation Clone ()
	{
		throw new NotImplementedException ();
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override float GetCurrentValueCore (float defaultOriginValue, float defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}
}


}
