
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class SingleKeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty; /* XXX initialize */
	public static readonly DependencyProperty ValueProperty; /* XXX initialize */

	protected SingleKeyFrame ()
	{
	}

	protected SingleKeyFrame (float value)
	{
	}

	protected SingleKeyFrame (float value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public float Value {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (float)value; }
	}

	public float InterpolateValue (float baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract float InterpolateValueCore (float baseValue, double keyFrameProgress);
}


}
