
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class SizeAnimation : SizeAnimationBase
{
	public static readonly DependencyProperty ByProperty; /* XXX initialize */
	public static readonly DependencyProperty FromProperty; /* XXX initialize */
	public static readonly DependencyProperty ToProperty; /* XXX initialize */

	public SizeAnimation ()
	{
	}

	public SizeAnimation (Size toValue, Duration duration)
	{
	}

	public SizeAnimation (Size toValue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public SizeAnimation (Size fromValue, Size toValue, Duration duration)
	{
	}

	public SizeAnimation (Size fromValue, Size tovalue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public Size? By {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public Size? From {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public Size? To {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public bool IsAdditive {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public bool IsCumulative {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public new SizeAnimation Clone ()
	{
		throw new NotImplementedException ();
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Size GetCurrentValueCore (Size defaultOriginValue, Size defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}
}


}
