
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class SizeAnimationBase : AnimationTimeline
{
	protected SizeAnimationBase () { }

	public override sealed Type TargetPropertyType { get { return typeof (Size); } }

	public new SizeAnimationBase Clone ()
	{
		throw new NotImplementedException ();
	} 

	public override sealed object GetCurrentValue (object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
	{
		return GetCurrentValue ((Size)defaultOriginValue, (Size) defaultDestinationValue, animationClock);
	}

	protected abstract Size GetCurrentValueCore (Size defaultOriginValue, Size defaultDestinationValue, AnimationClock animationClock);


	public Size GetCurrentValue (Size defaultOriginValue, Size defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}


}


}
