
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class SplineInt16KeyFrame : Int16KeyFrame
{

	public static readonly DependencyProperty KeySplineProperty; // XXX initialize

	short value;
	KeyTime keyTime;

	public SplineInt16KeyFrame ()
	{
	}

	public SplineInt16KeyFrame (short value)
	{
		this.value = value;
		// XX keytime?
	}

	public SplineInt16KeyFrame (short value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	public SplineInt16KeyFrame (short value, KeyTime keyTime, KeySpline keySpline)
	{
		this.value = value;
		this.keyTime = keyTime;
		KeySpline = keySpline;
	}

	public KeySpline KeySpline {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override short InterpolateValueCore (short baseValue, double keyFrameProgress)
	{
		double splineProgress = KeySpline.GetSplineProgress (keyFrameProgress);

		return (short)(baseValue + (value - baseValue) * splineProgress);
	}
}


}
