
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class SplineByteKeyFrame : ByteKeyFrame
{

	public static readonly DependencyProperty KeySplineProperty =
		DependencyProperty.Register ("KeySpline", typeof (KeySpline), typeof (SplineByteKeyFrame));

	byte value;
	KeyTime keyTime;

	public SplineByteKeyFrame ()
	{
	}

	public SplineByteKeyFrame (byte value)
	{
		this.value = value;
		// XX keytime?
	}

	public SplineByteKeyFrame (byte value, KeyTime keyTime)
	{
		this.value = value;
		this.keyTime = keyTime;
	}

	public SplineByteKeyFrame (byte value, KeyTime keyTime, KeySpline keySpline)
	{
		this.value = value;
		this.keyTime = keyTime;
		KeySpline = keySpline;
	}

	public KeySpline KeySpline {
		get { return (KeySpline)GetValue (KeySplineProperty); }
		set { SetValue (KeySplineProperty, value); }
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override byte InterpolateValueCore (byte baseValue, double keyFrameProgress)
	{
		double splineProgress = KeySpline.GetSplineProgress (keyFrameProgress);

		return (byte)(baseValue + (value - baseValue) * splineProgress);
	}
}


}
