
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class StringKeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty; /* XXX initialize */
	public static readonly DependencyProperty ValueProperty; /* XXX initialize */

	protected StringKeyFrame ()
	{
	}

	protected StringKeyFrame (String value)
	{
	}

	protected StringKeyFrame (String value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public String Value {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (String)value; }
	}

	public String InterpolateValue (String baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract String InterpolateValueCore (String baseValue, double keyFrameProgress);
}


}
