
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class VectorAnimationBase : AnimationTimeline
{
	protected VectorAnimationBase () { }

	public override sealed Type TargetPropertyType { get { return typeof (Vector); } }

	public new VectorAnimationBase Clone ()
	{
		throw new NotImplementedException ();
	} 

	public override sealed object GetCurrentValue (object defaultOriginValue, object defaultDestinationValue, AnimationClock animationClock)
	{
		return GetCurrentValue ((Vector)defaultOriginValue, (Vector) defaultDestinationValue, animationClock);
	}

	protected abstract Vector GetCurrentValueCore (Vector defaultOriginValue, Vector defaultDestinationValue, AnimationClock animationClock);


	public Vector GetCurrentValue (Vector defaultOriginValue, Vector defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}


}


}
