
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class VectorAnimation : VectorAnimationBase
{
	public static readonly DependencyProperty ByProperty
				= DependencyProperty.Register ("By", typeof (Vector), typeof (VectorKeyFrame));
	public static readonly DependencyProperty FromProperty
				= DependencyProperty.Register ("From", typeof (Vector), typeof (VectorKeyFrame));
	public static readonly DependencyProperty ToProperty
				= DependencyProperty.Register ("To", typeof (Vector), typeof (VectorKeyFrame));

	public VectorAnimation ()
	{
	}

	public VectorAnimation (Vector toValue, Duration duration)
	{
	}

	public VectorAnimation (Vector toValue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public VectorAnimation (Vector fromValue, Vector toValue, Duration duration)
	{
	}

	public VectorAnimation (Vector fromValue, Vector tovalue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public Vector? By {
		get { return (Vector?) GetValue (ByProperty); }
		set { SetValue (ByProperty, value); }
	}

	public Vector? From {
		get { return (Vector?) GetValue (FromProperty); }
		set { SetValue (FromProperty, value); }
	}

	public Vector? To {
		get { return (Vector?) GetValue (ToProperty); }
		set { SetValue (ToProperty, value); }
	}

	public bool IsAdditive {
		get { return (bool) GetValue (AnimationTimeline.IsAdditiveProperty); }
		set { SetValue (AnimationTimeline.IsAdditiveProperty, value); }
	}

	public bool IsCumulative {
		get { return (bool) GetValue (AnimationTimeline.IsCumulativeProperty); }
		set { SetValue (AnimationTimeline.IsCumulativeProperty, value); }
	}

	public new VectorAnimation Clone ()
	{
		throw new NotImplementedException ();
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Vector GetCurrentValueCore (Vector defaultOriginValue, Vector defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}
}


}
