
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public class VectorAnimation : VectorAnimationBase
{
	public static readonly DependencyProperty ByProperty; /* XXX initialize */
	public static readonly DependencyProperty FromProperty; /* XXX initialize */
	public static readonly DependencyProperty ToProperty; /* XXX initialize */

	public VectorAnimation ()
	{
	}

	public VectorAnimation (Vector toValue, Duration duration)
	{
	}

	public VectorAnimation (Vector toValue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public VectorAnimation (Vector fromValue, Vector toValue, Duration duration)
	{
	}

	public VectorAnimation (Vector fromValue, Vector tovalue, Duration duration, FillBehavior fillBehavior)
	{
	}

	public Vector? By {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public Vector? From {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public Vector? To {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public bool IsAdditive {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public bool IsCumulative {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public new VectorAnimation Clone ()
	{
		throw new NotImplementedException ();
	}

	protected override Freezable CreateInstanceCore ()
	{
		throw new NotImplementedException ();
	}

	protected override Vector GetCurrentValueCore (Vector defaultOriginValue, Vector defaultDestinationValue, AnimationClock animationClock)
	{
		throw new NotImplementedException ();
	}
}


}
