
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;

namespace System.Windows.Media.Animation {


public abstract class VectorKeyFrame : Freezable, IKeyFrame
{
	public static readonly DependencyProperty KeyTimeProperty; /* XXX initialize */
	public static readonly DependencyProperty ValueProperty; /* XXX initialize */

	protected VectorKeyFrame ()
	{
	}

	protected VectorKeyFrame (Vector value)
	{
	}

	protected VectorKeyFrame (Vector value, KeyTime keyTime)
	{
	}

	public KeyTime KeyTime {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	public Vector Value {
		get { throw new NotImplementedException (); }
		set { throw new NotImplementedException (); }
	}

	object IKeyFrame.Value {
		get { return Value; }
		set { Value = (Vector)value; }
	}

	public Vector InterpolateValue (Vector baseValue, double keyFrameProgress)
	{
		throw new NotImplementedException ();
	}

	protected abstract Vector InterpolateValueCore (Vector baseValue, double keyFrameProgress);
}


}
