thisdir = class/System.Silverlight
include ../../build/rules.make

LIBRARY = System.Windows.Browser.dll

LIB_MCS_FLAGS = -r:System -r:System.Net -r:Mono.Moonlight -noconfig -unsafe

include ../../build/library.make
