all: \
	samplesvc.exe samplecli.exe \
	samplesvc2.exe samplecli2.exe \
	samplesvc3.exe samplecli3.exe \
	samplesvc4.exe samplecli4.exe \
	samplesvc5.exe samplecli5.exe \
	samplesvc6.exe samplecli6.exe \
	samplesvc7.exe samplecli7.exe \
	samplesvc8.exe samplecli8.exe

samplesvc8.exe : samplesvc8.cs
	gmcs -pkg:olive samplesvc8.cs Inspector.cs

samplecli8.exe : samplecli8.cs
	gmcs -pkg:olive samplecli8.cs Inspector.cs

samplesvc7.exe : samplesvc7.cs
	gmcs -pkg:olive samplesvc7.cs Inspector.cs

samplecli7.exe : samplecli7.cs
	gmcs -pkg:olive samplecli7.cs Inspector.cs

samplesvc6.exe : samplesvc6.cs
	gmcs -pkg:olive samplesvc6.cs Inspector.cs

samplecli6.exe : samplecli6.cs
	gmcs -pkg:olive samplecli6.cs Inspector.cs

samplesvc5.exe : samplesvc5.cs
	gmcs -pkg:olive samplesvc5.cs Inspector.cs

samplecli5.exe : samplecli5.cs
	gmcs -pkg:olive samplecli5.cs Inspector.cs

samplesvc4.exe : samplesvc4.cs
	gmcs -pkg:olive samplesvc4.cs Inspector.cs

samplecli4.exe : samplecli4.cs
	gmcs -pkg:olive samplecli4.cs Inspector.cs

samplesvc3.exe : samplesvc3.cs
	gmcs -pkg:olive samplesvc3.cs Inspector.cs

samplecli3.exe : samplecli3.cs
	gmcs -pkg:olive samplecli3.cs Inspector.cs

samplesvc2.exe : samplesvc2.cs
	gmcs -pkg:olive samplesvc2.cs Inspector.cs

samplecli2.exe : samplecli2.cs
	gmcs -pkg:olive samplecli2.cs Inspector.cs

samplesvc.exe : samplesvc.cs Inspector.cs
	gmcs -pkg:olive samplesvc.cs Inspector.cs

samplecli.exe : samplecli.cs Inspector.cs
	gmcs -pkg:olive samplecli.cs Inspector.cs

clean:
	rm -f samplesvc.exe samplesvc.exe.mdb samplecli.exe samplecli.exe.mdb 
	rm -f samplesvc2.exe samplesvc2.exe.mdb samplecli2.exe samplecli2.exe.mdb 
	rm -f samplesvc3.exe samplesvc3.exe.mdb samplecli3.exe samplecli3.exe.mdb 
	rm -f samplesvc4.exe samplesvc4.exe.mdb samplecli4.exe samplecli4.exe.mdb 
	rm -f samplesvc5.exe samplesvc5.exe.mdb samplecli5.exe samplecli5.exe.mdb 
	rm -f samplesvc6.exe samplesvc6.exe.mdb samplecli6.exe samplecli6.exe.mdb 
	rm -f samplesvc7.exe samplesvc7.exe.mdb samplecli7.exe samplecli7.exe.mdb 
	rm -f samplesvc8.exe samplesvc8.exe.mdb samplecli8.exe samplecli8.exe.mdb 

