
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class BooleanKeyFrameTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("KeyTime", BooleanKeyFrame.KeyTimeProperty.Name, "1");
		Assert.AreEqual (typeof (BooleanKeyFrame), BooleanKeyFrame.KeyTimeProperty.OwnerType, "2");
		Assert.AreEqual (typeof (KeyTime), BooleanKeyFrame.KeyTimeProperty.PropertyType, "3");

		Assert.AreEqual ("Value", BooleanKeyFrame.ValueProperty.Name, "4");
		Assert.AreEqual (typeof (BooleanKeyFrame), BooleanKeyFrame.ValueProperty.OwnerType, "5");
		Assert.AreEqual (typeof (bool), BooleanKeyFrame.ValueProperty.PropertyType, "6");
	}
}


}
