
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class ByteAnimationTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("By", ByteAnimation.ByProperty.Name, "1");
		Assert.AreEqual (typeof (ByteAnimation), ByteAnimation.ByProperty.OwnerType, "2");
		Assert.AreEqual (typeof (byte?), ByteAnimation.ByProperty.PropertyType, "3");

		Assert.AreEqual ("From", ByteAnimation.FromProperty.Name, "4");
		Assert.AreEqual (typeof (ByteAnimation), ByteAnimation.FromProperty.OwnerType, "5");
		Assert.AreEqual (typeof (byte?), ByteAnimation.FromProperty.PropertyType, "6");

		Assert.AreEqual ("To", ByteAnimation.ToProperty.Name, "7");
		Assert.AreEqual (typeof (ByteAnimation), ByteAnimation.ToProperty.OwnerType, "8");
		Assert.AreEqual (typeof (byte?), ByteAnimation.ToProperty.PropertyType, "9");
	}
}


}
