
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class CharKeyFrameTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("KeyTime", CharKeyFrame.KeyTimeProperty.Name, "1");
		Assert.AreEqual (typeof (CharKeyFrame), CharKeyFrame.KeyTimeProperty.OwnerType, "2");
		Assert.AreEqual (typeof (KeyTime), CharKeyFrame.KeyTimeProperty.PropertyType, "3");

		Assert.AreEqual ("Value", CharKeyFrame.ValueProperty.Name, "4");
		Assert.AreEqual (typeof (CharKeyFrame), CharKeyFrame.ValueProperty.OwnerType, "5");
		Assert.AreEqual (typeof (char), CharKeyFrame.ValueProperty.PropertyType, "6");
	}
}


}
