
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class DecimalAnimationTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("By", DecimalAnimation.ByProperty.Name, "1");
		Assert.AreEqual (typeof (DecimalAnimation), DecimalAnimation.ByProperty.OwnerType, "2");
		Assert.AreEqual (typeof (Decimal?), DecimalAnimation.ByProperty.PropertyType, "3");

		Assert.AreEqual ("From", DecimalAnimation.FromProperty.Name, "4");
		Assert.AreEqual (typeof (DecimalAnimation), DecimalAnimation.FromProperty.OwnerType, "5");
		Assert.AreEqual (typeof (Decimal?), DecimalAnimation.FromProperty.PropertyType, "6");

		Assert.AreEqual ("To", DecimalAnimation.ToProperty.Name, "7");
		Assert.AreEqual (typeof (DecimalAnimation), DecimalAnimation.ToProperty.OwnerType, "8");
		Assert.AreEqual (typeof (Decimal?), DecimalAnimation.ToProperty.PropertyType, "9");
	}
}


}
