
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class DecimalKeyFrameTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("KeyTime", DecimalKeyFrame.KeyTimeProperty.Name, "1");
		Assert.AreEqual (typeof (DecimalKeyFrame), DecimalKeyFrame.KeyTimeProperty.OwnerType, "2");
		Assert.AreEqual (typeof (KeyTime), DecimalKeyFrame.KeyTimeProperty.PropertyType, "3");

		Assert.AreEqual ("Value", DecimalKeyFrame.ValueProperty.Name, "4");
		Assert.AreEqual (typeof (DecimalKeyFrame), DecimalKeyFrame.ValueProperty.OwnerType, "5");
		Assert.AreEqual (typeof (Decimal), DecimalKeyFrame.ValueProperty.PropertyType, "6");
	}
}


}
