
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class DoubleKeyFrameTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("KeyTime", DoubleKeyFrame.KeyTimeProperty.Name, "1");
		Assert.AreEqual (typeof (DoubleKeyFrame), DoubleKeyFrame.KeyTimeProperty.OwnerType, "2");
		Assert.AreEqual (typeof (KeyTime), DoubleKeyFrame.KeyTimeProperty.PropertyType, "3");

		Assert.AreEqual ("Value", DoubleKeyFrame.ValueProperty.Name, "4");
		Assert.AreEqual (typeof (DoubleKeyFrame), DoubleKeyFrame.ValueProperty.OwnerType, "5");
		Assert.AreEqual (typeof (double), DoubleKeyFrame.ValueProperty.PropertyType, "6");
	}
}


}
