
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class Int16AnimationBaseTest
{
	class Int16AnimationBasePoker : Int16AnimationBase
	{
		protected override short GetCurrentValueCore (short defaultOriginValue, short defaultDestinationValue,
							    AnimationClock animationClock)
		{
			throw new NotImplementedException ();
		}

		protected override Freezable CreateInstanceCore ()
		{
			throw new NotImplementedException ();
		}
	}

	[Test]
	public void Properties ()
	{
		Int16AnimationBasePoker poker = new Int16AnimationBasePoker ();
		Assert.AreEqual (typeof (short), poker.TargetPropertyType);
	}
}


}
