
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class Int16KeyFrameTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("KeyTime", Int16KeyFrame.KeyTimeProperty.Name, "1");
		Assert.AreEqual (typeof (Int16KeyFrame), Int16KeyFrame.KeyTimeProperty.OwnerType, "2");
		Assert.AreEqual (typeof (KeyTime), Int16KeyFrame.KeyTimeProperty.PropertyType, "3");

		Assert.AreEqual ("Value", Int16KeyFrame.ValueProperty.Name, "4");
		Assert.AreEqual (typeof (Int16KeyFrame), Int16KeyFrame.ValueProperty.OwnerType, "5");
		Assert.AreEqual (typeof (short), Int16KeyFrame.ValueProperty.PropertyType, "6");
	}
}


}
