
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class Int32KeyFrameTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("KeyTime", Int32KeyFrame.KeyTimeProperty.Name, "1");
		Assert.AreEqual (typeof (Int32KeyFrame), Int32KeyFrame.KeyTimeProperty.OwnerType, "2");
		Assert.AreEqual (typeof (KeyTime), Int32KeyFrame.KeyTimeProperty.PropertyType, "3");

		Assert.AreEqual ("Value", Int32KeyFrame.ValueProperty.Name, "4");
		Assert.AreEqual (typeof (Int32KeyFrame), Int32KeyFrame.ValueProperty.OwnerType, "5");
		Assert.AreEqual (typeof (int), Int32KeyFrame.ValueProperty.PropertyType, "6");
	}
}


}
