
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class Int32AnimationTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("By", Int32Animation.ByProperty.Name, "1");
		Assert.AreEqual (typeof (Int32Animation), Int32Animation.ByProperty.OwnerType, "2");
		Assert.AreEqual (typeof (int?), Int32Animation.ByProperty.PropertyType, "3");

		Assert.AreEqual ("From", Int32Animation.FromProperty.Name, "4");
		Assert.AreEqual (typeof (Int32Animation), Int32Animation.FromProperty.OwnerType, "5");
		Assert.AreEqual (typeof (int?), Int32Animation.FromProperty.PropertyType, "6");

		Assert.AreEqual ("To", Int32Animation.ToProperty.Name, "7");
		Assert.AreEqual (typeof (Int32Animation), Int32Animation.ToProperty.OwnerType, "8");
		Assert.AreEqual (typeof (int?), Int32Animation.ToProperty.PropertyType, "9");
	}
}


}
