
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class Int64AnimationTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("By", Int64Animation.ByProperty.Name, "1");
		Assert.AreEqual (typeof (Int64Animation), Int64Animation.ByProperty.OwnerType, "2");
		Assert.AreEqual (typeof (long?), Int64Animation.ByProperty.PropertyType, "3");

		Assert.AreEqual ("From", Int64Animation.FromProperty.Name, "4");
		Assert.AreEqual (typeof (Int64Animation), Int64Animation.FromProperty.OwnerType, "5");
		Assert.AreEqual (typeof (long?), Int64Animation.FromProperty.PropertyType, "6");

		Assert.AreEqual ("To", Int64Animation.ToProperty.Name, "7");
		Assert.AreEqual (typeof (Int64Animation), Int64Animation.ToProperty.OwnerType, "8");
		Assert.AreEqual (typeof (long?), Int64Animation.ToProperty.PropertyType, "9");
	}
}


}
