
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class Int64AnimationBaseTest
{
	class Int64AnimationBasePoker : Int64AnimationBase
	{
		protected override long GetCurrentValueCore (long defaultOriginValue, long defaultDestinationValue,
							    AnimationClock animationClock)
		{
			throw new NotImplementedException ();
		}

		protected override Freezable CreateInstanceCore ()
		{
			throw new NotImplementedException ();
		}
	}

	[Test]
	public void Properties ()
	{
		Int64AnimationBasePoker poker = new Int64AnimationBasePoker ();
		Assert.AreEqual (typeof (long), poker.TargetPropertyType);
	}
}


}
