
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class ObjectKeyFrameTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("KeyTime", ObjectKeyFrame.KeyTimeProperty.Name, "1");
		Assert.AreEqual (typeof (ObjectKeyFrame), ObjectKeyFrame.KeyTimeProperty.OwnerType, "2");
		Assert.AreEqual (typeof (KeyTime), ObjectKeyFrame.KeyTimeProperty.PropertyType, "3");

		Assert.AreEqual ("Value", ObjectKeyFrame.ValueProperty.Name, "4");
		Assert.AreEqual (typeof (ObjectKeyFrame), ObjectKeyFrame.ValueProperty.OwnerType, "5");
		Assert.AreEqual (typeof (object), ObjectKeyFrame.ValueProperty.PropertyType, "6");
	}
}


}
