
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class PointKeyFrameTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("KeyTime", PointKeyFrame.KeyTimeProperty.Name, "1");
		Assert.AreEqual (typeof (PointKeyFrame), PointKeyFrame.KeyTimeProperty.OwnerType, "2");
		Assert.AreEqual (typeof (KeyTime), PointKeyFrame.KeyTimeProperty.PropertyType, "3");

		Assert.AreEqual ("Value", PointKeyFrame.ValueProperty.Name, "4");
		Assert.AreEqual (typeof (PointKeyFrame), PointKeyFrame.ValueProperty.OwnerType, "5");
		Assert.AreEqual (typeof (Point), PointKeyFrame.ValueProperty.PropertyType, "6");
	}
}


}
