
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class PointAnimationTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("By", PointAnimation.ByProperty.Name, "1");
		Assert.AreEqual (typeof (PointAnimation), PointAnimation.ByProperty.OwnerType, "2");
		Assert.AreEqual (typeof (Point?), PointAnimation.ByProperty.PropertyType, "3");

		Assert.AreEqual ("From", PointAnimation.FromProperty.Name, "4");
		Assert.AreEqual (typeof (PointAnimation), PointAnimation.FromProperty.OwnerType, "5");
		Assert.AreEqual (typeof (Point?), PointAnimation.FromProperty.PropertyType, "6");

		Assert.AreEqual ("To", PointAnimation.ToProperty.Name, "7");
		Assert.AreEqual (typeof (PointAnimation), PointAnimation.ToProperty.OwnerType, "8");
		Assert.AreEqual (typeof (Point?), PointAnimation.ToProperty.PropertyType, "9");
	}
}


}
