
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class RectKeyFrameTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("KeyTime", RectKeyFrame.KeyTimeProperty.Name, "1");
		Assert.AreEqual (typeof (RectKeyFrame), RectKeyFrame.KeyTimeProperty.OwnerType, "2");
		Assert.AreEqual (typeof (KeyTime), RectKeyFrame.KeyTimeProperty.PropertyType, "3");

		Assert.AreEqual ("Value", RectKeyFrame.ValueProperty.Name, "4");
		Assert.AreEqual (typeof (RectKeyFrame), RectKeyFrame.ValueProperty.OwnerType, "5");
		Assert.AreEqual (typeof (Rect), RectKeyFrame.ValueProperty.PropertyType, "6");
	}
}


}
