
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class RectAnimationTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("By", RectAnimation.ByProperty.Name, "1");
		Assert.AreEqual (typeof (RectAnimation), RectAnimation.ByProperty.OwnerType, "2");
		Assert.AreEqual (typeof (Rect?), RectAnimation.ByProperty.PropertyType, "3");

		Assert.AreEqual ("From", RectAnimation.FromProperty.Name, "4");
		Assert.AreEqual (typeof (RectAnimation), RectAnimation.FromProperty.OwnerType, "5");
		Assert.AreEqual (typeof (Rect?), RectAnimation.FromProperty.PropertyType, "6");

		Assert.AreEqual ("To", RectAnimation.ToProperty.Name, "7");
		Assert.AreEqual (typeof (RectAnimation), RectAnimation.ToProperty.OwnerType, "8");
		Assert.AreEqual (typeof (Rect?), RectAnimation.ToProperty.PropertyType, "9");
	}
}


}
