
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class SizeKeyFrameTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("KeyTime", SizeKeyFrame.KeyTimeProperty.Name, "1");
		Assert.AreEqual (typeof (SizeKeyFrame), SizeKeyFrame.KeyTimeProperty.OwnerType, "2");
		Assert.AreEqual (typeof (KeyTime), SizeKeyFrame.KeyTimeProperty.PropertyType, "3");

		Assert.AreEqual ("Value", SizeKeyFrame.ValueProperty.Name, "4");
		Assert.AreEqual (typeof (SizeKeyFrame), SizeKeyFrame.ValueProperty.OwnerType, "5");
		Assert.AreEqual (typeof (Size), SizeKeyFrame.ValueProperty.PropertyType, "6");
	}
}


}
