
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class StringKeyFrameTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("KeyTime", StringKeyFrame.KeyTimeProperty.Name, "1");
		Assert.AreEqual (typeof (StringKeyFrame), StringKeyFrame.KeyTimeProperty.OwnerType, "2");
		Assert.AreEqual (typeof (KeyTime), StringKeyFrame.KeyTimeProperty.PropertyType, "3");

		Assert.AreEqual ("Value", StringKeyFrame.ValueProperty.Name, "4");
		Assert.AreEqual (typeof (StringKeyFrame), StringKeyFrame.ValueProperty.OwnerType, "5");
		Assert.AreEqual (typeof (String), StringKeyFrame.ValueProperty.PropertyType, "6");
	}
}


}
