
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class VectorAnimationBaseTest
{
	class VectorAnimationBasePoker : VectorAnimationBase
	{
		protected override Vector GetCurrentValueCore (Vector defaultOriginValue, Vector defaultDestinationValue,
							    AnimationClock animationClock)
		{
			throw new NotImplementedException ();
		}

		protected override Freezable CreateInstanceCore ()
		{
			throw new NotImplementedException ();
		}
	}

	[Test]
	public void Properties ()
	{
		VectorAnimationBasePoker poker = new VectorAnimationBasePoker ();
		Assert.AreEqual (typeof (Vector), poker.TargetPropertyType);
	}
}


}
