
/* this file is generated by gen-animation-types.cs.  do not modify */

using System;
using System.Collections;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Media.Animation;
using NUnit.Framework;

namespace MonoTests.System.Windows.Media.Animation {


[TestFixture]
public class VectorKeyFrameTest
{
	[Test]
	public void Properties ()
	{
		Assert.AreEqual ("KeyTime", VectorKeyFrame.KeyTimeProperty.Name, "1");
		Assert.AreEqual (typeof (VectorKeyFrame), VectorKeyFrame.KeyTimeProperty.OwnerType, "2");
		Assert.AreEqual (typeof (KeyTime), VectorKeyFrame.KeyTimeProperty.PropertyType, "3");

		Assert.AreEqual ("Value", VectorKeyFrame.ValueProperty.Name, "4");
		Assert.AreEqual (typeof (VectorKeyFrame), VectorKeyFrame.ValueProperty.OwnerType, "5");
		Assert.AreEqual (typeof (Vector), VectorKeyFrame.ValueProperty.PropertyType, "6");
	}
}


}
