thisdir = class/Microsoft.JScript.Compiler
include ../../build/rules.make

LIBRARY = Microsoft.JScript.Compiler.dll

LIB_MCS_FLAGS = -r:Microsoft.Scripting.dll -r:System.dll

include ../../build/library.make
