
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class DrawingCollection : Animatable, ICollection<Drawing>, IList<Drawing>, ICollection, IList
	{
		public struct Enumerator : IEnumerator<Drawing>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public Drawing Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public DrawingCollection ()
		{
		}

		public DrawingCollection (IEnumerable<Drawing> values)
		{
		}

		public DrawingCollection (int length)
		{
		}

		public DrawingCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public DrawingCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		protected override Freezable CreateInstanceCore ()
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		public bool Contains (Drawing value)
		{
			throw new NotImplementedException ();
		}

		public bool Remove (Drawing value)
		{
			throw new NotImplementedException ();
		}

		public int IndexOf (Drawing value)
		{
			throw new NotImplementedException ();
		}

		public void Add (Drawing value)
		{
			throw new NotImplementedException ();
		}

		public void Clear ()
		{
			throw new NotImplementedException ();
		}

		public void CopyTo (Drawing[] array, int offset)
		{
			throw new NotImplementedException ();
		}

		public void Insert (int index, Drawing value)
		{
			throw new NotImplementedException ();
		}

		public void RemoveAt (int index)
		{
			throw new NotImplementedException ();
		}

		public int Count {
			get { throw new NotImplementedException (); }
		}

		public Drawing this[int index] {
			get { throw new NotImplementedException (); }
			set { throw new NotImplementedException (); }
		}

		public static DrawingCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<Drawing>.IsReadOnly {
			get { return false; }
		}

		IEnumerator<Drawing> IEnumerable<Drawing>.GetEnumerator()
		{
			throw new NotImplementedException ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			throw new NotImplementedException ();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((Drawing[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (Drawing)value; }
		}

		int IList.Add (object value)
		{
			Add ((Drawing)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((Drawing)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((Drawing)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (Drawing)value);
		}

		void IList.Remove (object value)
		{
			Remove ((Drawing)value);
		}


		protected override bool FreezeCore (bool isChecking)
		{{
			throw new NotImplementedException ();
		}}
	}
}
