
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class GeneralTransformCollection : Animatable, ICollection<GeneralTransform>, IList<GeneralTransform>, ICollection, IList, IFormattable
	{
		List<GeneralTransform> list;

		public struct Enumerator : IEnumerator<GeneralTransform>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public GeneralTransform Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public GeneralTransformCollection ()
		{
			list = new List<GeneralTransform>();
		}

		public GeneralTransformCollection (IEnumerable<GeneralTransform> values)
		{
			list = new List<GeneralTransform> (values);
		}

		public GeneralTransformCollection (int length)
		{
			list = new List<GeneralTransform> (length);
		}

		public new GeneralTransformCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public new GeneralTransformCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		public bool Contains (GeneralTransform value)
		{
			return list.Contains (value);
		}

		public bool Remove (GeneralTransform value)
		{
			return list.Remove (value);
		}

		public int IndexOf (GeneralTransform value)
		{
			return list.IndexOf (value);
		}

		public void Add (GeneralTransform value)
		{
			list.Add (value);
		}

		public void Clear ()
		{
			list.Clear ();
		}

		public void CopyTo (GeneralTransform[] array, int arrayIndex)
		{
			list.CopyTo (array, arrayIndex);
		}

		public void Insert (int index, GeneralTransform value)
		{
			list.Insert (index, value);
		}

		public void RemoveAt (int index)
		{
			list.RemoveAt (index);
		}

		public int Count {
			get { return list.Count; }
		}

		public GeneralTransform this[int index] {
			get { return list[index]; }
			set { list[index] = value; }
		}

		public static GeneralTransformCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<GeneralTransform>.IsReadOnly {
			get { return false; }
		}

		public Enumerator GetEnumerator()
		{
			return new Enumerator();
		}

		IEnumerator<GeneralTransform> IEnumerable<GeneralTransform>.GetEnumerator()
		{
			return GetEnumerator ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			return GetEnumerator();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((GeneralTransform[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (GeneralTransform)value; }
		}

		int IList.Add (object value)
		{
			Add ((GeneralTransform)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((GeneralTransform)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((GeneralTransform)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (GeneralTransform)value);
		}

		void IList.Remove (object value)
		{
			Remove ((GeneralTransform)value);
		}

		public override string ToString ()
		{
			throw new NotImplementedException ();
		}

		public string ToString (IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}

		string IFormattable.ToString (string format, IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}


		protected override bool FreezeCore (bool isChecking)
		{{
			if (isChecking) {{
				return base.FreezeCore (isChecking);
			}}
			else {{
				return true;
			}}
		}}



		protected override Freezable CreateInstanceCore ()
		{
			return new GeneralTransformCollection();
		}

		protected override void GetAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}
	}
}
