
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class GeometryCollection : Animatable, ICollection<Geometry>, IList<Geometry>, ICollection, IList, IFormattable
	{
		List<Geometry> list;

		public struct Enumerator : IEnumerator<Geometry>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public Geometry Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public GeometryCollection ()
		{
			list = new List<Geometry>();
		}

		public GeometryCollection (IEnumerable<Geometry> values)
		{
			list = new List<Geometry> (values);
		}

		public GeometryCollection (int length)
		{
			list = new List<Geometry> (length);
		}

		public new GeometryCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public new GeometryCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		public bool Contains (Geometry value)
		{
			return list.Contains (value);
		}

		public bool Remove (Geometry value)
		{
			return list.Remove (value);
		}

		public int IndexOf (Geometry value)
		{
			return list.IndexOf (value);
		}

		public void Add (Geometry value)
		{
			list.Add (value);
		}

		public void Clear ()
		{
			list.Clear ();
		}

		public void CopyTo (Geometry[] array, int arrayIndex)
		{
			list.CopyTo (array, arrayIndex);
		}

		public void Insert (int index, Geometry value)
		{
			list.Insert (index, value);
		}

		public void RemoveAt (int index)
		{
			list.RemoveAt (index);
		}

		public int Count {
			get { return list.Count; }
		}

		public Geometry this[int index] {
			get { return list[index]; }
			set { list[index] = value; }
		}

		public static GeometryCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<Geometry>.IsReadOnly {
			get { return false; }
		}

		public Enumerator GetEnumerator()
		{
			return new Enumerator();
		}

		IEnumerator<Geometry> IEnumerable<Geometry>.GetEnumerator()
		{
			return GetEnumerator ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			return GetEnumerator();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((Geometry[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (Geometry)value; }
		}

		int IList.Add (object value)
		{
			Add ((Geometry)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((Geometry)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((Geometry)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (Geometry)value);
		}

		void IList.Remove (object value)
		{
			Remove ((Geometry)value);
		}

		public override string ToString ()
		{
			throw new NotImplementedException ();
		}

		public string ToString (IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}

		string IFormattable.ToString (string format, IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}


		protected override bool FreezeCore (bool isChecking)
		{{
			if (isChecking) {{
				return base.FreezeCore (isChecking);
			}}
			else {{
				return true;
			}}
		}}



		protected override Freezable CreateInstanceCore ()
		{
			return new GeometryCollection();
		}

		protected override void GetAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}
	}
}
