
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class GeometryCollection : Animatable, ICollection<Geometry>, IList<Geometry>, ICollection, IList
	{
		public struct Enumerator : IEnumerator<Geometry>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public Geometry Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public GeometryCollection ()
		{
		}

		public GeometryCollection (IEnumerable<Geometry> values)
		{
		}

		public GeometryCollection (int length)
		{
		}

		public GeometryCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public GeometryCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		protected override Freezable CreateInstanceCore ()
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		public bool Contains (Geometry value)
		{
			throw new NotImplementedException ();
		}

		public bool Remove (Geometry value)
		{
			throw new NotImplementedException ();
		}

		public int IndexOf (Geometry value)
		{
			throw new NotImplementedException ();
		}

		public void Add (Geometry value)
		{
			throw new NotImplementedException ();
		}

		public void Clear ()
		{
			throw new NotImplementedException ();
		}

		public void CopyTo (Geometry[] array, int offset)
		{
			throw new NotImplementedException ();
		}

		public void Insert (int index, Geometry value)
		{
			throw new NotImplementedException ();
		}

		public void RemoveAt (int index)
		{
			throw new NotImplementedException ();
		}

		public int Count {
			get { throw new NotImplementedException (); }
		}

		public Geometry this[int index] {
			get { throw new NotImplementedException (); }
			set { throw new NotImplementedException (); }
		}

		public static GeometryCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<Geometry>.IsReadOnly {
			get { return false; }
		}

		IEnumerator<Geometry> IEnumerable<Geometry>.GetEnumerator()
		{
			throw new NotImplementedException ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			throw new NotImplementedException ();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((Geometry[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (Geometry)value; }
		}

		int IList.Add (object value)
		{
			Add ((Geometry)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((Geometry)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((Geometry)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (Geometry)value);
		}

		void IList.Remove (object value)
		{
			Remove ((Geometry)value);
		}


		protected override bool FreezeCore (bool isChecking)
		{{
			throw new NotImplementedException ();
		}}
	}
}
