
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class GradientStopCollection : Animatable, ICollection<GradientStop>, IList<GradientStop>, ICollection, IList
	{
		public struct Enumerator : IEnumerator<GradientStop>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public GradientStop Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public GradientStopCollection ()
		{
		}

		public GradientStopCollection (IEnumerable<GradientStop> values)
		{
		}

		public GradientStopCollection (int length)
		{
		}

		public GradientStopCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public GradientStopCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		protected override Freezable CreateInstanceCore ()
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		public bool Contains (GradientStop value)
		{
			throw new NotImplementedException ();
		}

		public bool Remove (GradientStop value)
		{
			throw new NotImplementedException ();
		}

		public int IndexOf (GradientStop value)
		{
			throw new NotImplementedException ();
		}

		public void Add (GradientStop value)
		{
			throw new NotImplementedException ();
		}

		public void Clear ()
		{
			throw new NotImplementedException ();
		}

		public void CopyTo (GradientStop[] array, int offset)
		{
			throw new NotImplementedException ();
		}

		public void Insert (int index, GradientStop value)
		{
			throw new NotImplementedException ();
		}

		public void RemoveAt (int index)
		{
			throw new NotImplementedException ();
		}

		public int Count {
			get { throw new NotImplementedException (); }
		}

		public GradientStop this[int index] {
			get { throw new NotImplementedException (); }
			set { throw new NotImplementedException (); }
		}

		public static GradientStopCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<GradientStop>.IsReadOnly {
			get { return false; }
		}

		IEnumerator<GradientStop> IEnumerable<GradientStop>.GetEnumerator()
		{
			throw new NotImplementedException ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			throw new NotImplementedException ();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((GradientStop[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (GradientStop)value; }
		}

		int IList.Add (object value)
		{
			Add ((GradientStop)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((GradientStop)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((GradientStop)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (GradientStop)value);
		}

		void IList.Remove (object value)
		{
			Remove ((GradientStop)value);
		}


		protected override bool FreezeCore (bool isChecking)
		{{
			throw new NotImplementedException ();
		}}
	}
}
