
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class GradientStopCollection : Animatable, ICollection<GradientStop>, IList<GradientStop>, ICollection, IList, IFormattable
	{
		List<GradientStop> list;

		public struct Enumerator : IEnumerator<GradientStop>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public GradientStop Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public GradientStopCollection ()
		{
			list = new List<GradientStop>();
		}

		public GradientStopCollection (IEnumerable<GradientStop> values)
		{
			list = new List<GradientStop> (values);
		}

		public GradientStopCollection (int length)
		{
			list = new List<GradientStop> (length);
		}

		public new GradientStopCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public new GradientStopCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		public bool Contains (GradientStop value)
		{
			return list.Contains (value);
		}

		public bool Remove (GradientStop value)
		{
			return list.Remove (value);
		}

		public int IndexOf (GradientStop value)
		{
			return list.IndexOf (value);
		}

		public void Add (GradientStop value)
		{
			list.Add (value);
		}

		public void Clear ()
		{
			list.Clear ();
		}

		public void CopyTo (GradientStop[] array, int arrayIndex)
		{
			list.CopyTo (array, arrayIndex);
		}

		public void Insert (int index, GradientStop value)
		{
			list.Insert (index, value);
		}

		public void RemoveAt (int index)
		{
			list.RemoveAt (index);
		}

		public int Count {
			get { return list.Count; }
		}

		public GradientStop this[int index] {
			get { return list[index]; }
			set { list[index] = value; }
		}

		public static GradientStopCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<GradientStop>.IsReadOnly {
			get { return false; }
		}

		public Enumerator GetEnumerator()
		{
			return new Enumerator();
		}

		IEnumerator<GradientStop> IEnumerable<GradientStop>.GetEnumerator()
		{
			return GetEnumerator ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			return GetEnumerator();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((GradientStop[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (GradientStop)value; }
		}

		int IList.Add (object value)
		{
			Add ((GradientStop)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((GradientStop)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((GradientStop)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (GradientStop)value);
		}

		void IList.Remove (object value)
		{
			Remove ((GradientStop)value);
		}

		public override string ToString ()
		{
			throw new NotImplementedException ();
		}

		public string ToString (IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}

		string IFormattable.ToString (string format, IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}


		protected override bool FreezeCore (bool isChecking)
		{{
			if (isChecking) {{
				return base.FreezeCore (isChecking);
			}}
			else {{
				return true;
			}}
		}}



		protected override Freezable CreateInstanceCore ()
		{
			return new GradientStopCollection();
		}

		protected override void GetAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}
	}
}
