
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class Int32Collection : Freezable, ICollection<Int32>, IList<Int32>, ICollection, IList
	{
		public struct Enumerator : IEnumerator<Int32>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public Int32 Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public Int32Collection ()
		{
		}

		public Int32Collection (IEnumerable<Int32> values)
		{
		}

		public Int32Collection (int length)
		{
		}

		public Int32Collection Clone ()
		{
			throw new NotImplementedException ();
		}

		public Int32Collection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		protected override Freezable CreateInstanceCore ()
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		public bool Contains (int value)
		{
			throw new NotImplementedException ();
		}

		public bool Remove (int value)
		{
			throw new NotImplementedException ();
		}

		public int IndexOf (int value)
		{
			throw new NotImplementedException ();
		}

		public void Add (int value)
		{
			throw new NotImplementedException ();
		}

		public void Clear ()
		{
			throw new NotImplementedException ();
		}

		public void CopyTo (int[] array, int offset)
		{
			throw new NotImplementedException ();
		}

		public void Insert (int index, int value)
		{
			throw new NotImplementedException ();
		}

		public void RemoveAt (int index)
		{
			throw new NotImplementedException ();
		}

		public int Count {
			get { throw new NotImplementedException (); }
		}

		public int this[int index] {
			get { throw new NotImplementedException (); }
			set { throw new NotImplementedException (); }
		}

		public static Int32Collection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<Int32>.IsReadOnly {
			get { return false; }
		}

		IEnumerator<Int32> IEnumerable<Int32>.GetEnumerator()
		{
			throw new NotImplementedException ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			throw new NotImplementedException ();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((int[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (int)value; }
		}

		int IList.Add (object value)
		{
			Add ((int)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((int)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((int)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (int)value);
		}

		void IList.Remove (object value)
		{
			Remove ((int)value);
		}

	}
}
