
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class PathSegmentCollection : Animatable, ICollection<PathSegment>, IList<PathSegment>, ICollection, IList
	{
		public struct Enumerator : IEnumerator<PathSegment>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public PathSegment Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public PathSegmentCollection ()
		{
		}

		public PathSegmentCollection (IEnumerable<PathSegment> values)
		{
		}

		public PathSegmentCollection (int length)
		{
		}

		public PathSegmentCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public PathSegmentCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		protected override Freezable CreateInstanceCore ()
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		public bool Contains (PathSegment value)
		{
			throw new NotImplementedException ();
		}

		public bool Remove (PathSegment value)
		{
			throw new NotImplementedException ();
		}

		public int IndexOf (PathSegment value)
		{
			throw new NotImplementedException ();
		}

		public void Add (PathSegment value)
		{
			throw new NotImplementedException ();
		}

		public void Clear ()
		{
			throw new NotImplementedException ();
		}

		public void CopyTo (PathSegment[] array, int offset)
		{
			throw new NotImplementedException ();
		}

		public void Insert (int index, PathSegment value)
		{
			throw new NotImplementedException ();
		}

		public void RemoveAt (int index)
		{
			throw new NotImplementedException ();
		}

		public int Count {
			get { throw new NotImplementedException (); }
		}

		public PathSegment this[int index] {
			get { throw new NotImplementedException (); }
			set { throw new NotImplementedException (); }
		}

		public static PathSegmentCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<PathSegment>.IsReadOnly {
			get { return false; }
		}

		IEnumerator<PathSegment> IEnumerable<PathSegment>.GetEnumerator()
		{
			throw new NotImplementedException ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			throw new NotImplementedException ();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((PathSegment[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (PathSegment)value; }
		}

		int IList.Add (object value)
		{
			Add ((PathSegment)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((PathSegment)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((PathSegment)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (PathSegment)value);
		}

		void IList.Remove (object value)
		{
			Remove ((PathSegment)value);
		}


		protected override bool FreezeCore (bool isChecking)
		{{
			throw new NotImplementedException ();
		}}
	}
}
