
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class PathFigureCollection : Animatable, ICollection<PathFigure>, IList<PathFigure>, ICollection, IList
	{
		public struct Enumerator : IEnumerator<PathFigure>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public PathFigure Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public PathFigureCollection ()
		{
		}

		public PathFigureCollection (IEnumerable<PathFigure> values)
		{
		}

		public PathFigureCollection (int length)
		{
		}

		public PathFigureCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public PathFigureCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		protected override Freezable CreateInstanceCore ()
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		public bool Contains (PathFigure value)
		{
			throw new NotImplementedException ();
		}

		public bool Remove (PathFigure value)
		{
			throw new NotImplementedException ();
		}

		public int IndexOf (PathFigure value)
		{
			throw new NotImplementedException ();
		}

		public void Add (PathFigure value)
		{
			throw new NotImplementedException ();
		}

		public void Clear ()
		{
			throw new NotImplementedException ();
		}

		public void CopyTo (PathFigure[] array, int offset)
		{
			throw new NotImplementedException ();
		}

		public void Insert (int index, PathFigure value)
		{
			throw new NotImplementedException ();
		}

		public void RemoveAt (int index)
		{
			throw new NotImplementedException ();
		}

		public int Count {
			get { throw new NotImplementedException (); }
		}

		public PathFigure this[int index] {
			get { throw new NotImplementedException (); }
			set { throw new NotImplementedException (); }
		}

		public static PathFigureCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<PathFigure>.IsReadOnly {
			get { return false; }
		}

		IEnumerator<PathFigure> IEnumerable<PathFigure>.GetEnumerator()
		{
			throw new NotImplementedException ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			throw new NotImplementedException ();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((PathFigure[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (PathFigure)value; }
		}

		int IList.Add (object value)
		{
			Add ((PathFigure)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((PathFigure)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((PathFigure)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (PathFigure)value);
		}

		void IList.Remove (object value)
		{
			Remove ((PathFigure)value);
		}


		protected override bool FreezeCore (bool isChecking)
		{{
			throw new NotImplementedException ();
		}}
	}
}
