
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class PointCollection : Freezable, ICollection<Point>, IList<Point>, ICollection, IList, IFormattable
	{
		List<Point> list;

		public struct Enumerator : IEnumerator<Point>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public Point Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public PointCollection ()
		{
			list = new List<Point>();
		}

		public PointCollection (IEnumerable<Point> values)
		{
			list = new List<Point> (values);
		}

		public PointCollection (int length)
		{
			list = new List<Point> (length);
		}

		public new PointCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public new PointCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		public bool Contains (Point value)
		{
			return list.Contains (value);
		}

		public bool Remove (Point value)
		{
			return list.Remove (value);
		}

		public int IndexOf (Point value)
		{
			return list.IndexOf (value);
		}

		public void Add (Point value)
		{
			list.Add (value);
		}

		public void Clear ()
		{
			list.Clear ();
		}

		public void CopyTo (Point[] array, int arrayIndex)
		{
			list.CopyTo (array, arrayIndex);
		}

		public void Insert (int index, Point value)
		{
			list.Insert (index, value);
		}

		public void RemoveAt (int index)
		{
			list.RemoveAt (index);
		}

		public int Count {
			get { return list.Count; }
		}

		public Point this[int index] {
			get { return list[index]; }
			set { list[index] = value; }
		}

		public static PointCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<Point>.IsReadOnly {
			get { return false; }
		}

		public Enumerator GetEnumerator()
		{
			return new Enumerator();
		}

		IEnumerator<Point> IEnumerable<Point>.GetEnumerator()
		{
			return GetEnumerator ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			return GetEnumerator();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((Point[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (Point)value; }
		}

		int IList.Add (object value)
		{
			Add ((Point)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((Point)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((Point)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (Point)value);
		}

		void IList.Remove (object value)
		{
			Remove ((Point)value);
		}

		public override string ToString ()
		{
			throw new NotImplementedException ();
		}

		public string ToString (IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}

		string IFormattable.ToString (string format, IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}


		protected override Freezable CreateInstanceCore ()
		{
			return new PointCollection();
		}

		protected override void GetAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}
	}
}
