
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class PointCollection : Freezable, ICollection<Point>, IList<Point>, ICollection, IList
	{
		public struct Enumerator : IEnumerator<Point>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public Point Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public PointCollection ()
		{
		}

		public PointCollection (IEnumerable<Point> values)
		{
		}

		public PointCollection (int length)
		{
		}

		public PointCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public PointCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		protected override Freezable CreateInstanceCore ()
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		public bool Contains (Point value)
		{
			throw new NotImplementedException ();
		}

		public bool Remove (Point value)
		{
			throw new NotImplementedException ();
		}

		public int IndexOf (Point value)
		{
			throw new NotImplementedException ();
		}

		public void Add (Point value)
		{
			throw new NotImplementedException ();
		}

		public void Clear ()
		{
			throw new NotImplementedException ();
		}

		public void CopyTo (Point[] array, int offset)
		{
			throw new NotImplementedException ();
		}

		public void Insert (int index, Point value)
		{
			throw new NotImplementedException ();
		}

		public void RemoveAt (int index)
		{
			throw new NotImplementedException ();
		}

		public int Count {
			get { throw new NotImplementedException (); }
		}

		public Point this[int index] {
			get { throw new NotImplementedException (); }
			set { throw new NotImplementedException (); }
		}

		public static PointCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<Point>.IsReadOnly {
			get { return false; }
		}

		IEnumerator<Point> IEnumerable<Point>.GetEnumerator()
		{
			throw new NotImplementedException ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			throw new NotImplementedException ();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((Point[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (Point)value; }
		}

		int IList.Add (object value)
		{
			Add ((Point)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((Point)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((Point)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (Point)value);
		}

		void IList.Remove (object value)
		{
			Remove ((Point)value);
		}

	}
}
