
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class PointCollectionConverter : TypeConverter
	{
		public override bool CanConvertFrom (ITypeDescriptorContext context, Type type)
		{
			throw new NotImplementedException ();
		}

		public override object ConvertFrom (ITypeDescriptorContext context, CultureInfo culture, object value)
		{
			throw new NotImplementedException (); 
		}

		public override bool CanConvertTo (ITypeDescriptorContext context, Type type)
		{
			throw new NotImplementedException ();
		}

		public override object ConvertTo (ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType)
		{
			throw new NotImplementedException (); 
		}

	}
}
