
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class TransformCollection : Animatable, ICollection<Transform>, IList<Transform>, ICollection, IList, IFormattable
	{
		List<Transform> list;

		public struct Enumerator : IEnumerator<Transform>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public Transform Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public TransformCollection ()
		{
			list = new List<Transform>();
		}

		public TransformCollection (IEnumerable<Transform> values)
		{
			list = new List<Transform> (values);
		}

		public TransformCollection (int length)
		{
			list = new List<Transform> (length);
		}

		public new TransformCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public new TransformCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		public bool Contains (Transform value)
		{
			return list.Contains (value);
		}

		public bool Remove (Transform value)
		{
			return list.Remove (value);
		}

		public int IndexOf (Transform value)
		{
			return list.IndexOf (value);
		}

		public void Add (Transform value)
		{
			list.Add (value);
		}

		public void Clear ()
		{
			list.Clear ();
		}

		public void CopyTo (Transform[] array, int arrayIndex)
		{
			list.CopyTo (array, arrayIndex);
		}

		public void Insert (int index, Transform value)
		{
			list.Insert (index, value);
		}

		public void RemoveAt (int index)
		{
			list.RemoveAt (index);
		}

		public int Count {
			get { return list.Count; }
		}

		public Transform this[int index] {
			get { return list[index]; }
			set { list[index] = value; }
		}

		public static TransformCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<Transform>.IsReadOnly {
			get { return false; }
		}

		public Enumerator GetEnumerator()
		{
			return new Enumerator();
		}

		IEnumerator<Transform> IEnumerable<Transform>.GetEnumerator()
		{
			return GetEnumerator ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			return GetEnumerator();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((Transform[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (Transform)value; }
		}

		int IList.Add (object value)
		{
			Add ((Transform)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((Transform)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((Transform)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (Transform)value);
		}

		void IList.Remove (object value)
		{
			Remove ((Transform)value);
		}

		public override string ToString ()
		{
			throw new NotImplementedException ();
		}

		public string ToString (IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}

		string IFormattable.ToString (string format, IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}


		protected override Freezable CreateInstanceCore ()
		{
			return new TransformCollection();
		}

		protected override void GetAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}
	}
}
