
/* this file is generated by gen-collection-types.cs.  do not modify */

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Windows.Media.Animation;

namespace System.Windows.Media {


	public class VectorCollection : Freezable, ICollection<Vector>, IList<Vector>, ICollection, IList, IFormattable
	{
		List<Vector> list;

		public struct Enumerator : IEnumerator<Vector>, IEnumerator
		{
			public void Reset()
			{
				throw new NotImplementedException (); 
			}

			public bool MoveNext()
			{
				throw new NotImplementedException (); 
			}

			public Vector Current {
				get { throw new NotImplementedException (); }
			}

			object IEnumerator.Current {
				get { return Current; }
			}

			void IDisposable.Dispose()
			{
			}
		}

		public VectorCollection ()
		{
			list = new List<Vector>();
		}

		public VectorCollection (IEnumerable<Vector> values)
		{
			list = new List<Vector> (values);
		}

		public VectorCollection (int length)
		{
			list = new List<Vector> (length);
		}

		public new VectorCollection Clone ()
		{
			throw new NotImplementedException ();
		}

		public new VectorCollection CloneCurrentValue ()
		{
			throw new NotImplementedException ();
		}

		public bool Contains (Vector value)
		{
			return list.Contains (value);
		}

		public bool Remove (Vector value)
		{
			return list.Remove (value);
		}

		public int IndexOf (Vector value)
		{
			return list.IndexOf (value);
		}

		public void Add (Vector value)
		{
			list.Add (value);
		}

		public void Clear ()
		{
			list.Clear ();
		}

		public void CopyTo (Vector[] array, int arrayIndex)
		{
			list.CopyTo (array, arrayIndex);
		}

		public void Insert (int index, Vector value)
		{
			list.Insert (index, value);
		}

		public void RemoveAt (int index)
		{
			list.RemoveAt (index);
		}

		public int Count {
			get { return list.Count; }
		}

		public Vector this[int index] {
			get { return list[index]; }
			set { list[index] = value; }
		}

		public static VectorCollection Parse (string str)
		{
			throw new NotImplementedException ();
		}

		bool ICollection<Vector>.IsReadOnly {
			get { return false; }
		}

		public Enumerator GetEnumerator()
		{
			return new Enumerator();
		}

		IEnumerator<Vector> IEnumerable<Vector>.GetEnumerator()
		{
			return GetEnumerator ();
		}

		IEnumerator IEnumerable.GetEnumerator ()
		{
			return GetEnumerator();
		}

		bool ICollection.IsSynchronized {
			get { return false; }
		}

		object ICollection.SyncRoot {
			get { return this; }
		}

		void ICollection.CopyTo(Array array, int offset)
		{
			CopyTo ((Vector[]) array, offset);
		}

		bool IList.IsFixedSize {
			get { return false; }
		}

		bool IList.IsReadOnly {
			get { return false; }
		}

		object IList.this[int index] {
			get { return this[index]; }
			set { this[index] = (Vector)value; }
		}

		int IList.Add (object value)
		{
			Add ((Vector)value);
			return Count;
		}

		bool IList.Contains (object value)
		{
			return Contains ((Vector)value);
		}

		int IList.IndexOf (object value)
		{
			return IndexOf ((Vector)value);
		}

		void IList.Insert (int index, object value)
		{
			Insert (index, (Vector)value);
		}

		void IList.Remove (object value)
		{
			Remove ((Vector)value);
		}

		public override string ToString ()
		{
			throw new NotImplementedException ();
		}

		public string ToString (IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}

		string IFormattable.ToString (string format, IFormatProvider provider)
		{
			throw new NotImplementedException ();
		}


		protected override Freezable CreateInstanceCore ()
		{
			return new VectorCollection();
		}

		protected override void GetAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void GetCurrentValueAsFrozenCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCurrentValueCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}

		protected override void CloneCore (Freezable sourceFreezable)
		{
			throw new NotImplementedException ();
		}
	}
}
