thisdir = class/UIAutomationTypes
include ../../build/rules.make

LIBRARY = UIAutomationTypes.dll

LIB_MCS_FLAGS = -r:System -r:WindowsBase
TEST_MCS_FLAGS = $(LIB_MCS_FLAGS) -r:UIAutomationTypes.dll

include ../../build/library.make
