thisdir = tools/linqmapper
SUBDIRS = 
include ../../build/rules.make

LOCAL_MCS_FLAGS = \
                  /r:System.dll
                  /r:System.Xml.dll
                  /r:System.Data.Linq.dll
                  /r:System.Data.Linq.Design.dll
                  /r:Mono.GetOptions.dll

PROGRAM = linqmapper.exe

include ../../build/executable.make