thisdir = class/PresentationCore
include ../../build/rules.make

LIBRARY = PresentationCore.dll

LIB_MCS_FLAGS = -r:WindowsBase.dll -r:System.dll -nowarn:0067,0414

TEST_MCS_FLAGS = -r:WindowsBase.dll

include ../../build/library.make
