thisdir = class/Microsoft.JScript.Runtime
include ../../build/rules.make

LIBRARY = Microsoft.JScript.Runtime.dll

LIB_MCS_FLAGS = -r:Microsoft.Scripting.dll -r:System.dll

TEST_MCS_FLAGS = $(LIB_MCS_FLAGS)

include ../../build/library.make
